export const patients = [
  {
    id: 'DEM-2026-001',
    name: 'Amine Mansouri',
    initials: 'AM',
    age: 27,
    room: '12',
    bed: 'A',
    status: 'À surveiller',
    updated: '19:10',
    tone: 'blue',
  },
  {
    id: 'DEM-2026-002',
    name: 'Sarah Benali',
    initials: 'SB',
    age: 34,
    room: '14',
    bed: 'B',
    status: 'Stable',
    updated: '18:45',
    tone: 'violet',
  },
  {
    id: 'DEM-2026-003',
    name: 'Yacine Aït',
    initials: 'YA',
    age: 52,
    room: '15',
    bed: 'A',
    status: 'Urgent',
    updated: '18:30',
    tone: 'orange',
  },
  {
    id: 'DEM-2026-004',
    name: 'Nadia Cherif',
    initials: 'NC',
    age: 46,
    room: '16',
    bed: 'B',
    status: 'Stable',
    updated: '18:12',
    tone: 'green',
  },
  {
    id: 'DEM-2026-005',
    name: 'Lina Haddad',
    initials: 'LH',
    age: 62,
    room: '18',
    bed: 'A',
    status: 'Stable',
    updated: '17:50',
    tone: 'rose',
  },
  {
    id: 'DEM-2026-006',
    name: 'Omar Meziane',
    initials: 'OM',
    age: 39,
    room: '19',
    bed: 'B',
    status: 'Sortie',
    updated: '17:20',
    tone: 'slate',
  },
]
